### ISSUE TITLE
QAutocomplete2 will be installed in the wrong place?

### ISSUE THREAD

**Issue by kukrik** [qcubed/plugin_autocomplete2#6]
After the command line should go to the folder "vendor/qcubed/plugin". But here, instead put the folder "vendor/qcubed".

Let me give just a bug report!

**Comment by spekary** [comment]
Working on it. Composer broke.

**Comment by spekary** [comment]
Fixed. This was a problem created by Composer 8 days ago, and a problem with the version number of the latest release here. Run composer update, or just 
```
composer update qcubed\composer
```
to get the latest installer.

**Comment by kukrik** [comment]
:+1:

**Comment by kukrik** [comment]
This topic may be closed.
